# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: saralaprojects
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: awsnodejs
# "service" is the name of this project. This will also be added to your AWS resource names.
service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.randomNumberGenerator
